#!/usr/bin/env ruby

require 'bundler/setup'
require 'gcp_directory'

GcpDirectory.directory = ARGV[0] || raise('first argument must by listening directory')

# list for files
GcpDirectory::Listener.listen
